name: Publish to TestPyPI

on:
    release:
        types: [created]

jobs:
    build-n-deploy:
        name: Build and deploy Python distribution to TestPyPI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python 3.6
              uses: actions/setup-python@v1
              with:
                  python-version: 3.6
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install setuptools wheel twine
            - name: Build and upload to PyPI
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: $${{ secrets.TEST_PYPI_DEPLOYMENT_TOKEN }}
              run: |
                  python setup.py sdist bdist_wheel
                  twine upload dist/*
